# Basic R packages to load and save datasets
install.packages("BiocManager")
install.packages("https://cran.rstudio.com/src/contrib/matrixStats_0.58.0.tar.gz", repo=NULL, type="source")
install.packages("uwot")
BiocManager::install('SingleCellExperiment')
BiocManager::install('jsonlite')
BiocManager::install('Matrix')
BiocManager::install('scater')
BiocManager::install('scran')
install.packages("R.utils")
