# Basic R packages to load and save datasets
install.packages("BiocManager")
install.packages("optparse")
install.packages("https://cran.rstudio.com/src/contrib/matrixStats_0.58.0.tar.gz", repo=NULL, type="source")
BiocManager::install('jsonlite')
BiocManager::install('Matrix')
BiocManager::install('SingleCellExperiment')
install.packages("R.utils")
install.packages("magrittr")
install.packages("dplyr")
install.packages("devtools")
